app/ascii/views.py
import urllib2 # pragma: no cover
import requests # pragma: no cover
import json # pragma: no cover
import logging
from app import app, db, cache, bcrypt # pragma: no cover
from flask import render_template, request, url_for, redirect, flash, abort, Blueprint # pragma: no cover
from flask_login import current_user, login_required

from app.users.models import Users
from app.ascii.models import AsciiArt # pragma: no cover
from app.ascii.forms import AsciiForm # pragma: no cover

ascii_blueprint = Blueprint("ascii", __name__, template_folder="templates")

def get_ip():
    headers_list = request.headers.getlist("X-Forwarded-For")
    user_ip = headers_list[0] if headers_list else request.remote_addr
    return user_ip

IP_URL = "http://ip-api.com/json/"
def get_coords(ip):
    ip = get_ip()
    try:
        url = IP_URL + ip
    except TypeError:
        url = IP_URL + "73.55.103.114"
    content = None
    try:
        content = urllib2.urlopen(url).read()
    except URLError:
        return
    if content:
        try:
            result = json.loads(content)
            lat = float(result["lat"])
            lon = float(result["lon"])
            return (lat,lon)
        except KeyError:
            lat = "50.00"
            lon = "50.00"
            return (lat,lon)
    else:
        return None

def gmaps_img(points):
    GMAPS_URL = "https://maps.googleapis.com/maps/api/staticmap?size=550x400&zoom=3&sensor=false&key=AIzaSyDOnmHKt4bMXj-QL8pKeHd4yCyTL8-IzUc"
    for lat, lon in points:
        GMAPS_URL += '&markers=%s,%s' % (lat, lon)
    return GMAPS_URL

def top_arts(update=False):
    key = "top"
    all_art = cache.get(key)
    if all_art is None or update:
        logging.error("DB QUERY")
        all_art = AsciiArt.query.order_by(AsciiArt.id.desc()).all()
        all_art = list(all_art)
        cache.set(key, all_art)
    return all_art

def top_users(update=False):
    key = "all_uses"
    all_users = cache.get(key)
    if all_users is None or update:
        logging.error("Users DB QUERY")
        all_users = Users.query.all()
        all_users = list(all_users)
        cache.set(key, all_users)
    return all_users 

@ascii_blueprint.route("/ascii", methods=["GET","POST"])
@login_required
def hello():
    all_art = top_arts()
    all_users = top_users()
    form = AsciiForm()
    ip = get_ip()
    error = None
    lat = [a.lat for a in all_art]
    lon = [b.lon for b in all_art]
    gps = zip(lat,lon)
    img_url = None
    img_url = gmaps_img(gps)
    if form.validate_on_submit():
        one = AsciiArt(title=form.title.data, art=form.art.data, user_id=current_user.id)
        lat = get_coords(ip)[0]
        lon = get_coords(ip)[1]
        if lat and lon:
            one.lat = lat
            one.lon = lon
        db.session.add(one)
        db.session.commit()
        top_arts(True)
        top_users(True)
        flash("You just posted some <strong>ascii</strong> artwork!", "success")
        return redirect(url_for("hello"))
    return render_template("front.html", 
        all_art=all_art,
        all_users=all_users, 
        img_url=img_url, 
        form=form, 
        error=error)

@ascii_blueprint.route("/<int:art_id>/edit", methods=["GET","POST"])
@login_required
def edit_art(art_id):
    all_art = top_arts()
    all_users = top_users()
    lat = [a.lat for a in all_art]
    lon = [b.lon for b in all_art]
    gps = zip(lat,lon)
    img_url = None
    img_url = gmaps_img(gps)
    error = None
    edit_art = AsciiArt.query.filter_by(id=art_id).one()
    form = AsciiForm(obj=edit_art)
    if form.validate_on_submit():
        edit_art.title = form.title.data
        edit_art.art = form.art.data
        db.session.add(edit_art)
        db.session.commit()
        top_arts(True)
        top_users(True)
        flash("Successful Edit of <strong>%s</strong>" % edit_art.title, "info")
        return redirect(url_for("hello"))
    return render_template("edit.html", 
        error=error, 
        edit_art=edit_art, 
        form=form, 
        all_art=all_art,
        all_users=all_users, 
        img_url=img_url)

@ascii_blueprint.route("/<int:art_id>/delete", methods=["GET","POST"])
@login_required
def delete_art(art_id):
    delete_artwork = AsciiArt.query.filter_by(id=art_id).one()
    form = AsciiForm()
    if request.method == "POST":
        db.session.delete(delete_artwork)
        db.session.commit()
        top_arts(True)
        top_users(True)
        flash("Just deleted <u>%s</u>" % delete_artwork.title, "danger")
        return redirect(url_for("hello"))
    return render_template("delete.html", 
        delete_artwork=delete_artwork)

@ascii_blueprint.route("/ajax", methods=["GET","POST"])
@login_required
def ajax():    
    return render_template("ajax.html")

@ascii_blueprint.route("/puppy-api-example", methods=["GET", "POST"])
@login_required
def pup_api():
    url = "http://adopt-puppy.herokuapp.com/shelters/.json"
    response = requests.get(url)
    shelters = response.json()
    return render_template("pup-api.html", shelters=shelters)


app/promo/views.py
from app import app, db, mail
from flask import Blueprint, render_template
from flask_mail import Message


promo_blueprint = Blueprint("promo", __name__, template_folder="templates")

@promo_blueprint.route("/testmail")
def testmail():

    msg = Message("Hello", recipients=["jeffreiher@gmail.com"])
    msg.body = "testing"
    msg.html = "<b>Testing</b>"
    mail.send(msg)
    return "sent"

@promo_blueprint.route("/tos")
def tos():
    return render_template("termsofservice.html")

@promo_blueprint.route("/private-policy")
def private_policy():
    return render_template("privacypolicy.html")

app/users/views.py
import datetime
from app import app, db, cache, bcrypt 
from flask import render_template, url_for, redirect, request, Blueprint, flash, session
from flask_login import login_user, logout_user, login_required, current_user
from app.users.forms import LoginForm, RegistrationForm, RecoverPasswordForm, ChangePasswordTokenForm
from app.users.models import Users, UserRoles
from app.users.utils import get_ip, is_safe_url, generate_confirmation_token, confirm_token, \
send_email, password_reset_email, email_reset_notice

users_blueprint = Blueprint("users", __name__, template_folder="templates")

@users_blueprint.route("/login", methods=["GET","POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        if user is not None and bcrypt.check_password_hash(user.password,form.password.data):
            remember_me = form.remember_me.data
            user.login_count += 1
            user.last_login_ip = user.current_login_ip
            user.last_login_at = user.current_login_at
            user.current_login_ip = get_ip()
            user.current_login_at = datetime.datetime.now()
            db.session.add(user)
            db.session.commit()
            cache.clear()
            login_user(user, remember=remember_me)
            next = request.args.get("next")
            if not is_safe_url(next):
                return flask.abort(400)
            flash("You just logged in as %s!" % user.email, "success")
            return redirect(url_for('ascii.hello'))
        else:
            flash("<strong>Invalid password.</strong> Please try again.", "danger")
            return redirect(url_for("users.login"))
    return render_template("login.html", form=form)

@users_blueprint.route("/", methods=["GET","POST"])
def signup():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = Users(
            email=form.email.data,
            password = form.password.data,
            login_count = 1,
            current_login_ip = get_ip(),
            current_login_at = datetime.datetime.now()
            )
        try:
            db.session.add(user)
            db.session.commit()
            cache.clear()
            token = generate_confirmation_token(user.email)
            confirm_url = url_for('users.confirm_email_register', token=token, _external=True)
            html = render_template("email/welcome.html", confirm_url=confirm_url, user=user)
            subject = "Please confirm your email"
            send_email(user.email, subject, html)
            login_user(user)
            flash("You have just signup up congrats!", "success")
            next = request.args.get("next")
            if not is_safe_url(next):
                return flask.abort(400)
            return redirect(next or url_for("ascii.hello"))
        except:
            flash("That email already exists", "danger")
            return redirect(url_for("users.signup"))
    return render_template("signup.html", form=form)

@users_blueprint.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You just successfully logged out", "danger")
    cache.clear()
    referer = request.headers["Referer"]
    return redirect(referer)

@users_blueprint.route('/confirm/<token>/')
@login_required
def confirm_email_register(token):
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or has expired.', 'danger')
    user = Users.query.filter_by(email=email).first_or_404()
    if user.confirmed:
        flash('Account already confirmed. Please login.', 'success')
    else:
        user.confirmed = True
        user.confirmed_at = datetime.datetime.now()
        user_roles = UserRoles(user_id=user.id, role_id=1)
        db.session.add_all([user, user_roles])
        db.session.commit()
        cache.clear()
        flash('You have confirmed your account. Thanks!', 'success')
    return redirect(url_for('ascii.hello'))

@users_blueprint.route("/forgot-password/", methods=["GET","POST"])
def forgot_password():
    form = RecoverPasswordForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data, confirmed=False).one_or_none()
        if user is not None:
            password_reset_email(user.email)
            flash("sent email to %s" % user.email, "warning")
            return redirect(url_for("users.login"))
        else:
            flash("this account is not confirmed", "danger")
            return redirect(url_for("users.login"))
    return render_template("forgot_password.html", form=form)

@users_blueprint.route("/password-reset/<token>/", methods=["GET","POST"])
def forgot_password_reset_token(token):
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or has expired.', 'danger')
    user = Users.query.filter_by(email=email).one_or_none()
    form = ChangePasswordTokenForm()
    if request.method == "POST": 
        user.password = request.form["password"]
        db.session.add(user)
        db.session.commit()
        email_reset_notice(user.email)
        flash("Successful password updated!", "success")
        cache.clear()
        return redirect(url_for("users.login"))
    return render_template("forgot_password_change.html", form=form, token=token)

app/promo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/ico" href="{{ url_for('static', filename='composite.ico') }}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" >
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <title>{% block title %}{% endblock %}</title>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-80819767-1', 'auto');
      ga('send', 'pageview');

    </script>
</head>
<body>
    <nav class="navbar">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('ascii.hello') }}">AsciiChan-Tripplannr.com</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('ascii.hello') }}">/ascii-chan/</a></li>
                <li><a href="{{ url_for('ascii.ajax') }}">/trip planner/</a></li>
                <li><a href="{{ url_for('ascii.pup_api') }}">/puppy api example/</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_active %}
                <li><a href="{{ url_for('users.logout') }}">{{ current_user.username }}</a></li>
                <li><a href="{{ url_for('users.logout') }}">logout</a></li>
            {% else %}
                <li><a href="{{ url_for('users.login') }}">login</a></li>
            {% endif %}
            </ul>
        </div>
    </nav>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            {% include "message_flashes.html" %}
        </div>
    </div>
</div><!-- end container -->
{% block content %}{% endblock %}
<div id="wrap"></div>
<footer>
    <div class="container">
        <p class="text-center copyright"><a href="#">Copyright &#169; asciichan-tripplannr.com 2016</a></p>
        <p class="text-center"><a href="{{ url_for('promo.private_policy') }}">Private Policy</a></p>
        <p class="text-center tos"><a href="{{ url_for('promo.tos') }}">Terms of Service</a></p>
    </div>
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<script src="{{ url_for('static', filename='script.js') }}"></script>
<script TYPE="text/javascript"> function popup(mylink, windowname) { if (! window.focus)return true; var href; if (typeof(mylink) == 'string') href=mylink; else href=mylink.href; window.open(href, windowname, 'width=700,height=400,scrollbars=yes'); return false; } </script>

Read more: http://html.com/javascript/popup-windows/#ixzz4UiAgjIs5
</body>
</html>

app/promo/templates/message_flashes.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {{ message | safe }}
    </div>  
    {% endfor %}
    {% endif %}
{% endwith %}