app/ascii/models.py
import datetime # pragma: no cover
from app import db # pragma: no cover

class AsciiArt(db.Model):
    
    __tablename__ = 'asciiart'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String)
    art = db.Column(db.String)
    created = db.Column(db.Date, default=datetime.datetime.now())
    lon = db.Column(db.Float)
    lat = db.Column(db.Float)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    user = db.relationship("Users", lazy='subquery')

    @property 
    def format_date(self):
        return '{dt:%A} {dt:%B} {dt.day}, {dt.year}'.format(dt=self.created)

    def __repr__(self):
        return '<title>: {}'.format(self.title)

app/ascii/forms.py
from flask_wtf import Form 
from wtforms import TextField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length

class AsciiForm(Form):
    title = TextField("Title", validators=[DataRequired(message="Hey, you need a title."), Length(max=75, message="Hey, that title is a little long.")])
    art = TextAreaField("Art", validators=[DataRequired(message="Hey buddy, you need to paste in some ascii artwork.")])
    submit = SubmitField("post artwork")

app/ascii/views.py
import urllib2 # pragma: no cover
import requests # pragma: no cover
import json # pragma: no cover
import logging
from app import app, db, cache, bcrypt # pragma: no cover
from flask import render_template, request, url_for, redirect, flash, abort, Blueprint # pragma: no cover
from flask_login import current_user, login_required

from app.users.models import Users
from app.ascii.models import AsciiArt # pragma: no cover
from app.ascii.forms import AsciiForm # pragma: no cover

ascii_blueprint = Blueprint("ascii", __name__, template_folder="templates")

def get_ip():
    headers_list = request.headers.getlist("X-Forwarded-For")
    user_ip = headers_list[0] if headers_list else request.remote_addr
    return user_ip

IP_URL = "http://ip-api.com/json/"
def get_coords(ip):
    ip = get_ip()
    try:
        url = IP_URL + ip
    except TypeError:
        url = IP_URL + "73.55.103.114"
    content = None
    try:
        content = urllib2.urlopen(url).read()
    except URLError:
        return
    if content:
        try:
            result = json.loads(content)
            lat = float(result["lat"])
            lon = float(result["lon"])
            return (lat,lon)
        except KeyError:
            lat = "50.00"
            lon = "50.00"
            return (lat,lon)
    else:
        return None

def gmaps_img(points):
    GMAPS_URL = "https://maps.googleapis.com/maps/api/staticmap?size=550x400&zoom=3&sensor=false&key=AIzaSyDOnmHKt4bMXj-QL8pKeHd4yCyTL8-IzUc"
    for lat, lon in points:
        GMAPS_URL += '&markers=%s,%s' % (lat, lon)
    return GMAPS_URL

def top_arts(update=False):
    key = "top"
    all_art = cache.get(key)
    if all_art is None or update:
        logging.error("DB QUERY")
        all_art = AsciiArt.query.order_by(AsciiArt.id.desc()).all()
        all_art = list(all_art)
        cache.set(key, all_art)
    return all_art

def top_users(update=False):
    key = "all_uses"
    all_users = cache.get(key)
    if all_users is None or update:
        logging.error("Users DB QUERY")
        all_users = Users.query.all()
        all_users = list(all_users)
        cache.set(key, all_users)
    return all_users 

@ascii_blueprint.route("/ascii", methods=["GET","POST"])
@login_required
def hello():
    all_art = top_arts()
    all_users = top_users()
    form = AsciiForm()
    ip = get_ip()
    error = None
    lat = [a.lat for a in all_art]
    lon = [b.lon for b in all_art]
    gps = zip(lat,lon)
    img_url = None
    img_url = gmaps_img(gps)
    if form.validate_on_submit():
        one = AsciiArt(title=form.title.data, art=form.art.data, user_id=current_user.id)
        lat = get_coords(ip)[0]
        lon = get_coords(ip)[1]
        if lat and lon:
            one.lat = lat
            one.lon = lon
        db.session.add(one)
        db.session.commit()
        top_arts(True)
        top_users(True)
        flash("You just posted some <strong>ascii</strong> artwork!", "success")
        return redirect(url_for("hello"))
    return render_template("front.html", 
        all_art=all_art,
        all_users=all_users, 
        img_url=img_url, 
        form=form, 
        error=error)

@ascii_blueprint.route("/<int:art_id>/edit", methods=["GET","POST"])
@login_required
def edit_art(art_id):
    all_art = top_arts()
    all_users = top_users()
    lat = [a.lat for a in all_art]
    lon = [b.lon for b in all_art]
    gps = zip(lat,lon)
    img_url = None
    img_url = gmaps_img(gps)
    error = None
    edit_art = AsciiArt.query.filter_by(id=art_id).one()
    form = AsciiForm(obj=edit_art)
    if form.validate_on_submit():
        edit_art.title = form.title.data
        edit_art.art = form.art.data
        db.session.add(edit_art)
        db.session.commit()
        top_arts(True)
        top_users(True)
        flash("Successful Edit of <strong>%s</strong>" % edit_art.title, "info")
        return redirect(url_for("hello"))
    return render_template("edit.html", 
        error=error, 
        edit_art=edit_art, 
        form=form, 
        all_art=all_art,
        all_users=all_users, 
        img_url=img_url)

@ascii_blueprint.route("/<int:art_id>/delete", methods=["GET","POST"])
@login_required
def delete_art(art_id):
    delete_artwork = AsciiArt.query.filter_by(id=art_id).one()
    form = AsciiForm()
    if request.method == "POST":
        db.session.delete(delete_artwork)
        db.session.commit()
        top_arts(True)
        top_users(True)
        flash("Just deleted <u>%s</u>" % delete_artwork.title, "danger")
        return redirect(url_for("hello"))
    return render_template("delete.html", 
        delete_artwork=delete_artwork)

@ascii_blueprint.route("/ajax", methods=["GET","POST"])
@login_required
def ajax():    
    return render_template("ajax.html")

@ascii_blueprint.route("/puppy-api-example", methods=["GET", "POST"])
@login_required
def pup_api():
    url = "http://adopt-puppy.herokuapp.com/shelters/.json"
    response = requests.get(url)
    shelters = response.json()
    return render_template("pup-api.html", shelters=shelters)


app/ascii/templates/ajax.html
{% extends "base.html" %}
{% block title %}trip planner{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form class="form-inline text-center" id="form-container">
                <div class="form-group">
                    <label for="street" class="sr-only">Street</label>
                    <input type="text" id="street" name="street" class="form-control" placeholder="Enter a street address...">
                </div>
                <div class="form-group">
                    <label for="city" class="sr-only">City</label>
                    <input type="text" name="city" id="city" class="form-control" placeholder="Enter a city...">
                </div>
                <div class="form-group">
                    <label for="state" class="sr-only">State</label>
                    <input type="text" name="state" id="state" class="form-control" placeholder="Enter a state...">
                </div>
                <input type="submit" class="btn front-button" value="Search">
            </form>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-12">
            <div id="body"></div>
            <h3 id="greeting" class="greeting text-center">Where do you want to live?</h3>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-8 text-center">
            <h3 id="nytimes-header center-block">New York Times Articles</h3>
            <ul class="list-unstyled" id="nytimes-articles"> Whats's going on in your new city?  Enter an address and hit submit and the NY Times will tell you here!</ul>
        </div>
        <div class="col-md-4">
            <h3 id="wikipedia-header">Relevant Wikipedia Links</h3>
            <ul id="wikipedia-links">Type in an address above and find relevant Wikipedia articles here!</ul>
        </div>
    </div>
</div>
{% endblock %}

app/ascii/templates/delete.html
{% extends "base.html" %}
{% block title %}Delete{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center">You sure you want to delete <u>{{ delete_artwork.title }}</u>?</h1>
            <form method="post" action="" class="delete text-center">
                <input class="btn front-button" type="submit" value="Delete Item">
                <a class="btn blue" href="/">Cancel</a>
            </form>
        </div>
    </div>
</div>
<div id="wrap"></div>
{% endblock %}

app/ascii/templates/edit.html
{% extends "base.html" %}
{% block title %}Edit{% endblock %}
{% block content %}
<div class="container">
    <h2>/edit/</h2>
    <div class="row">
        <div class="col-md-6">
            <form method="POST" action="">
                {{ form.csrf_token }}
                <div class="form-group">
                    {{ form.title.label(for="title", class="sr-only") }}
                    {{ form.title(class="form-control", id="title", type="text", placeholder="give your artwork a title...") }}
                    <span class="bg-danger">
                        {% if form.title.errors %}
                        {% for error in form.title.errors %}
                        <div class="bg-danger">{{ error }}</div>
                        {% endfor %}
                        {% endif %}
                    </span>
                </div>
                <div class="form-group">
                    {{ form.art.label(for="art", class="sr-only") }}
                    {{ form.art(class="form-control", id="art", rows="10", placeholder="paste your ascii artwork here...") }}
                    <span class="error bg-danger">
                        {% if form.art.errors %}
                        {% for error in form.art.errors %}
                        <div class="bg-danger">{{ error }}</div>
                        {% endfor %}
                        {% endif %}
                    </span>
                </div>
                <div class="form-group">
                    {{ form.submit(class="btn front-button", value="edit") }}
                    <a class="btn blue" href="/">Cancel</a>
                </div>
            </form>
        </div> <!-- end col-md-6 -->
        <div class="col-md-6">
            <img src="{{ img_url }}">
        </div>
    </div> <!-- end row 2 -->
    <hr>
    <div class="row">
    {% for art in all_art %}
    
        <div class="col-md-6 showart">
            
        <div class="pull-right" style="padding-top:5px;">
            {% if current_user.id == art.user_id %}
            <a href="{{ url_for('edit_art',art_id=art.id) }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp;edit</a>&nbsp;|&nbsp;<a href="{{ url_for('delete_art', art_id=art.id) }}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span>&nbsp;delete</a>
            {% endif %}
        </div> 
        <p class="text-capitalize h3">{{ art.title }}</p>
        <p class="text-muted">{{ art.format_date }}</p>
        <p><strong>Lat:</strong>&nbsp;{{ art.lat }}&nbsp;&nbsp;<strong>Lon:</strong>&nbsp;{{ art.lon }}</p>
        {% for user in all_users %}
            {% if user.id == art.user_id %}
                <p><strong>Posted by: </strong>{{ user.username }}</p>
            {% endif %}
        {% endfor %}
        <hr>
        <div class="justart">
        <pre>{{ art.art }}</pre>
        </div>
        
        <br>
    </div>
     {% endfor %}
     
    </div>
</div>
{% endblock %}

app/ascii/templates/front.html
{% extends "base.html" %}
{% block title %}ascii chan{% endblock %}
{% block content %}
<div class="container">
    <h2>/ascii/</h2>
    <div class="row">
        <div class="col-md-6">
            <form method="POST" action="">
                {{ form.csrf_token }}
                <div class="form-group">
                    {{ form.title.label(for="title", class="sr-only") }}
                    {{ form.title(class="form-control", id="title", type="text", placeholder="give your artwork a title...") }}
                    <span class="bg-danger">
                        {% if form.title.errors %}
                        {% for error in form.title.errors %}
                        <div class="bg-danger">{{ error }}</div>
                        {% endfor %}
                        {% endif %}
                    </span>
                </div>
                <div class="form-group">
                    {{ form.art.label(for="art", class="sr-only") }}
                    {{ form.art(class="form-control", id="art", rows="10", placeholder="paste your ascii artwork here...") }}
                    <span class="error bg-danger">
                        {% if form.art.errors %}
                        {% for error in form.art.errors %}
                        <div class="bg-danger">{{ error }}</div>
                        {% endfor %}
                        {% endif %}
                    </span>
                </div>
                <div class="form-group">
                    {{ form.submit(class="btn front-button") }}
                </div>
            </form>
        </div> <!-- end col-md-6 -->
                
        <div class="col-md-6">
            <img class="img-responsive" src="{{ img_url }}">
        </div>
    </div> <!-- end row 2 -->
    <hr>

    <div class="row">
    {% for art in all_art %}
    
        <div class="col-md-6 showart">
            
        <div class="pull-right" style="padding-top:5px;">
            {% if current_user.id == art.user_id %}
            <a href="{{ url_for('ascii.edit_art',art_id=art.id) }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp;edit</a>&nbsp;|&nbsp;<a href="{{ url_for('ascii.delete_art', art_id=art.id) }}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span>&nbsp;delete</a>
            {% endif %}
        </div> 
        <p class="text-capitalize h3">{{ art.title }}</p>
        <p class="text-muted">{{ art.format_date }}</p>
        <p><strong>Lat:</strong>&nbsp;{{ art.lat }}&nbsp;&nbsp;<strong>Lon:</strong>&nbsp;{{ art.lon }}</p>
        {% for user in all_users %}
            {% if user.id == art.user_id %}
                <p><strong>Posted by: </strong>{{ user.username }}</p>
            {% endif %}
        {% endfor %}
        <hr>
        <div class="justart">
        <pre>{{ art.art }}</pre>
        </div>
        
        <br>
    </div>
     {% endfor %}
     
    </div>
</div>
{% endblock %}

app/ascii/templates/pup-api.html
{% extends "base.html" %}
{% block title %}api-usage{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <blockquote>
            <p class="h2">This page was made to show that I can create and use api's.</p>
            <p>I created an API on this <a href="http://adopt-puppy.herokuapp.com/shelters/.json" target="_blank">site</a> and I have used it down below. Try it out go <a href="http://adopt-puppy.herokuapp.com/new-shelter" target="_blank">here</a> and add a shelter, then come back to this page and see it show up.</p>
            </blockquote>
        </div>
    </div>
</div>
<br>
<div class="container">
<hr>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <ul class="list-unstyled">
                <p class="h4">Shelters from <a href="http://adopt-puppy.herokuapp.com/" target="_blank">http://adopt-puppy.herokuapp.com/</a></p>
                {% for key, value in shelters.items() %}
                    {#{{ key }} {{ value }}#}
                    {% for v in value %}
                        <li>{{ v['name'] }}</li>
                    {% endfor %}
                {% endfor %}
            </ul>
        </div>
    </div>
<hr>
</div>
<br>
{% endblock %}