app/users/models.py
import datetime 
from app import db, bcrypt, uploaded_photos 
from sqlalchemy.ext.hybrid import hybrid_property
from flask_security import UserMixin, RoleMixin

class Users(db.Model):

    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String, unique=True)
    _password = db.Column(db.String)
    confirmed = db.Column(db.Boolean(), default=False)
    confirmed_at = db.Column(db.DateTime)
    date_created = db.Column(db.DateTime,  default=datetime.datetime.utcnow)
    date_modified = db.Column(db.DateTime, nullable=True, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)
    last_login_at = db.Column(db.DateTime)
    last_login_ip = db.Column(db.String(45))
    current_login_at = db.Column(db.DateTime)
    current_login_ip = db.Column(db.String(45))
    login_count = db.Column(db.Integer, default=0)
    asciiart = db.relationship("AsciiArt", lazy='subquery')
    roles = db.relationship('Role', secondary='user_roles', backref=db.backref('users', lazy='dynamic', cascade="all, delete-orphan", single_parent=True))

    @hybrid_property 
    def password(self):
        return self._password 

    @password.setter 
    def _set_password(self, plaintext):
        self._password = bcrypt.generate_password_hash(plaintext)

    def is_authenticated():
        return True

    def is_active():
        return True

    def is_anonymous():
        return False 

    def has_role(self, role):
        if role in self.roles:
            return True
        else:
            return False

    def get_id(self):
        return unicode(self.id)

# Define the Role DataModel
class Role(db.Model, RoleMixin):
    __tablename__ = "role"

    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(50), unique=True)
    description = db.Column(db.String(255))

    def __repr__(self):
        return '<Role %r>' % self.name

class UserRoles(db.Model):
    __tablename__ = "user_roles"
    
    id = db.Column(db.Integer(), primary_key=True)
    user_id = db.Column(db.Integer(), db.ForeignKey('users.id', ondelete='CASCADE'), index=True)
    role_id = db.Column(db.Integer(), db.ForeignKey('role.id', ondelete='CASCADE'), index=True)


app/users/forms.py
from flask_wtf import Form 
from wtforms import TextField, SubmitField, PasswordField, BooleanField
from wtforms.fields.html5 import EmailField
from wtforms.validators import DataRequired, Length, EqualTo, Email

class LoginForm(Form):
    email = EmailField("Email", validators=[DataRequired(message="You need to put in a username"), Email()])
    password = PasswordField("Password", validators=[DataRequired(message="You need to enter a password"), Length(min=4,max=35, message="Your password needs to be between 4 and 35 chars")])
    remember_me = BooleanField("&nbsp;Remember Me")
    submit = SubmitField("Login")

class RegistrationForm(Form):
    email = EmailField("Email", validators=[DataRequired(message="You need to put in a username"), Email()])
    password = PasswordField('New Password', validators=[DataRequired(), EqualTo('confirm', message='Passwords must match')])
    confirm = PasswordField('Repeat Password')
    accept_tos = BooleanField('&nbsp;I accept the TOS', validators=[DataRequired(message="You need to accept the TOS.")])
    submit = SubmitField("Sign Up")

class RecoverPasswordForm(Form):
    email = EmailField("Email", [DataRequired(), Email()])
    submit = SubmitField("Reset Password")

class ChangePasswordTokenForm(Form):
    password = PasswordField("Password", [DataRequired(), Length(min=12, message="The min password length is 12 chars long.")])
    password_confirm = PasswordField("Confirm", [DataRequired(), EqualTo("password", message="Your passwords don't match.")])
    submit = SubmitField("Change Password")

app/promo/views.py
from app import app, db, mail
from flask import Blueprint, render_template
from flask_mail import Message


promo_blueprint = Blueprint("promo", __name__, template_folder="templates")

@promo_blueprint.route("/testmail")
def testmail():

    msg = Message("Hello", recipients=["jeffreiher@gmail.com"])
    msg.body = "testing"
    msg.html = "<b>Testing</b>"
    mail.send(msg)
    return "sent"

@promo_blueprint.route("/tos")
def tos():
    return render_template("termsofservice.html")

@promo_blueprint.route("/private-policy")
def private_policy():
    return render_template("privacypolicy.html")

app/users/views.py
import datetime
from app import app, db, cache, bcrypt 
from flask import render_template, url_for, redirect, request, Blueprint, flash, session
from flask_login import login_user, logout_user, login_required, current_user
from app.users.forms import LoginForm, RegistrationForm, RecoverPasswordForm, ChangePasswordTokenForm
from app.users.models import Users, UserRoles
from app.users.utils import get_ip, is_safe_url, generate_confirmation_token, confirm_token, \
send_email, password_reset_email, email_reset_notice

users_blueprint = Blueprint("users", __name__, template_folder="templates")

@users_blueprint.route("/login", methods=["GET","POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        if user is not None and bcrypt.check_password_hash(user.password,form.password.data):
            remember_me = form.remember_me.data
            user.login_count += 1
            user.last_login_ip = user.current_login_ip
            user.last_login_at = user.current_login_at
            user.current_login_ip = get_ip()
            user.current_login_at = datetime.datetime.now()
            db.session.add(user)
            db.session.commit()
            cache.clear()
            login_user(user, remember=remember_me)
            next = request.args.get("next")
            if not is_safe_url(next):
                return flask.abort(400)
            flash("You just logged in as %s!" % user.email, "success")
            return redirect(url_for('ascii.hello'))
        else:
            flash("<strong>Invalid password.</strong> Please try again.", "danger")
            return redirect(url_for("users.login"))
    return render_template("login.html", form=form)

@users_blueprint.route("/", methods=["GET","POST"])
def signup():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = Users(
            email=form.email.data,
            password = form.password.data,
            login_count = 1,
            current_login_ip = get_ip(),
            current_login_at = datetime.datetime.now()
            )
        try:
            db.session.add(user)
            db.session.commit()
            cache.clear()
            token = generate_confirmation_token(user.email)
            confirm_url = url_for('users.confirm_email_register', token=token, _external=True)
            html = render_template("email/welcome.html", confirm_url=confirm_url, user=user)
            subject = "Please confirm your email"
            send_email(user.email, subject, html)
            login_user(user)
            flash("You have just signup up congrats!", "success")
            next = request.args.get("next")
            if not is_safe_url(next):
                return flask.abort(400)
            return redirect(next or url_for("ascii.hello"))
        except:
            flash("That email already exists", "danger")
            return redirect(url_for("users.signup"))
    return render_template("signup.html", form=form)

@users_blueprint.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You just successfully logged out", "danger")
    cache.clear()
    referer = request.headers["Referer"]
    return redirect(referer)

@users_blueprint.route('/confirm/<token>/')
@login_required
def confirm_email_register(token):
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or has expired.', 'danger')
    user = Users.query.filter_by(email=email).first_or_404()
    if user.confirmed:
        flash('Account already confirmed. Please login.', 'success')
    else:
        user.confirmed = True
        user.confirmed_at = datetime.datetime.now()
        user_roles = UserRoles(user_id=user.id, role_id=1)
        db.session.add_all([user, user_roles])
        db.session.commit()
        cache.clear()
        flash('You have confirmed your account. Thanks!', 'success')
    return redirect(url_for('ascii.hello'))

@users_blueprint.route("/forgot-password/", methods=["GET","POST"])
def forgot_password():
    form = RecoverPasswordForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data, confirmed=False).one_or_none()
        if user is not None:
            password_reset_email(user.email)
            flash("sent email to %s" % user.email, "warning")
            return redirect(url_for("users.login"))
        else:
            flash("this account is not confirmed", "danger")
            return redirect(url_for("users.login"))
    return render_template("forgot_password.html", form=form)

@users_blueprint.route("/password-reset/<token>/", methods=["GET","POST"])
def forgot_password_reset_token(token):
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or has expired.', 'danger')
    user = Users.query.filter_by(email=email).one_or_none()
    form = ChangePasswordTokenForm()
    if request.method == "POST": 
        user.password = request.form["password"]
        db.session.add(user)
        db.session.commit()
        email_reset_notice(user.email)
        flash("Successful password updated!", "success")
        cache.clear()
        return redirect(url_for("users.login"))
    return render_template("forgot_password_change.html", form=form, token=token)

app/users/templates/_macros.html
{% macro render_field_with_errors(field) %}
    {#{{ field.label }}#} {{ field(**kwargs)|safe }}
    {% if field.errors %}
      <ul class="signup-error">
      {% for error in field.errors %}
        <li class="signup-error-li">{{ error }}</li>
      {% endfor %}
      </ul>
    {% endif %}
{% endmacro %}

{% macro render_field(field) %}
  <p>{{ field(**kwargs)|safe }}</p>
{% endmacro %}

app/users/templates/_menu.html
{% if security.registerable or security.recoverable or security.confirmable %}
<h2>Menu</h2>
<ul>
  <li><a href="{{ url_for_security('login') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}">Login</a></li>
  {% if security.registerable %}
  <li><a href="{{ url_for_security('register') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}">Register</a><br/></li>
  {% endif %}
  {% if security.recoverable %}
  <li><a href="{{ url_for_security('forgot_password') }}">Forgot password</a><br/></li>
  {% endif %}
  {% if security.confirmable %}
  <li><a href="{{ url_for_security('send_confirmation') }}">Confirm account</a></li>
  {% endif %}
</ul>
{% endif %}

app/users/templates/forgot_password.html
{% extends "base.html" %}
{% block title %}Forgot Password{% endblock %}
{% block content %}
{% from "_macros.html" import render_field_with_errors, render_field %}
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <div class="signup-border">
            <h3 class="text-center">Recover Password</h3>
            <hr>
            <form action="{{ url_for('users.forgot_password') }}" method="POST">
              {{ form.csrf_token }}
              <div class="form-group">
                 {{ render_field_with_errors(form.email, class="form-control", placeholder="email address...") }} 
              </div>
              <div class="form-group">
                 {{ render_field(form.submit, class="btn btn-danger btn-block") }}
              </div>
            </form>
          </div>
        </div>
    </div>
</div>
{% endblock %}

app/users/templates/forgot_password_change.html
{% extends "base.html" %}
{% block title %}Forgot Password{% endblock %}
{% block style %}
{% endblock %}
{% block content %}
<div class="container">
{% from "_macros.html" import render_field_with_errors, render_field %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <div class="signup-border">
            <h3 class="text-center">Reset Password</h3>
            <hr>
            <form id="registerForm" action="{{ url_for('users.forgot_password_reset_token', token=token) }}" method="POST">
              {{ form.csrf_token }}
              <div class="form-group">
              {{ render_field_with_errors(form.password, class="form-control", placeholder="password...") }}
              </div>
              <div class="form-group">
              {{ render_field_with_errors(form.password_confirm, class="form-control", placeholder="confirm password...") }}
              </div>
              <div class="form-group">
              {{ form.submit(class="btn btn-primary btn-block") }}
              </div>
            </form>
        </div>
      </div>
    </div>
</div>    
{% endblock %}

app/users/templates/login.html
{% extends "base.html" %}
{% block title %}trip planner{% endblock %}
{% block content %}
{% from "_macros.html" import render_field_with_errors, render_field %}

<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="signup-border">
                <h2 class="text-center">Login</h2>
                <form method="post" action="{{ url_for('users.login') }}">
                    {{ form.csrf_token }}
                    <div class="form-group">
                        {{ form.email.label(class="sr-only") }}
                        {{ render_field_with_errors(form.email, class="form-control input-lg", placeholder="email address...") }}
                    </div>
                    <div class="form-group">
                        {{ form.password.label(class="sr-only") }}
                        {{ render_field_with_errors(form.password, class="form-control input-lg", placeholder="password...") }}
                    </div>
                    <div class="form-group">
                        {{ form.remember_me }} {{ form.remember_me.label }}
                        <li class="pull-right"><a href="{{ url_for('users.forgot_password') }}">Forgot password</a><br/></li>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Login" class="form-control input-lg signup-button">
                    </div>
                </form>
                <br><br>
                <p><small class="text-muted">don't have an account yet?</small>  <a href="{{ url_for('users.signup') }}">&nbsp;register here</p>
                <hr>
            </div>
        </div>
    </div>
</div>


{% endblock %}

app/users/templates/signup.html
{% extends "base.html" %}
{% block title %}trip planner{% endblock %}
{% block content %}
{% from "_macros.html" import render_field_with_errors, render_field %}

<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="signup-border">
                <h2 class="text-center">Sign up</h2>
                <hr>
                <h4 class="text-center">Sign up to receive Internet's best offers</h4>
                <form method="post" action="">
                    {{ form.csrf_token }}
                    <div class="form-group">
                        {{ form.email.label(class="sr-only") }}
                        {{ render_field_with_errors(form.email, class="form-control input-lg", placeholder="email address...") }}
                    </div>
                    <div class="form-group">
                        {{ form.password.label(class="sr-only") }}
                        {{ render_field_with_errors(form.password, class="form-control input-lg", placeholder="choose a password...") }}
                    </div>
                    <div class="form-group">
                        {{ form.confirm.label(class="sr-only") }}
                        {{ render_field_with_errors(form.confirm, class="form-control input-lg", placeholder="confirm password...") }}
                    </div>
                    <div class="form-group">
                         {{ render_field_with_errors(form.accept_tos,class="pull-left") }}&nbsp;{{ form.accept_tos.label }}&nbsp;<small class="text-muted"><a href="{{ url_for('promo.tos') }}" onClick="return popup(this, 'notes')">(Click to Read)</a></small>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="form-control input-lg signup-button">
                    </div>
                </form>
                <br><br>
                <p>already have an account?  <a href="{{ url_for('users.login') }}">login here</p>
                <hr>
            </div>
        </div>
    </div>
</div>
{% endblock %}